chore: implement an indicator horizontal list
factorialco/factorial-one pull request #482
Opened 2024-09-10 17:00 UTC by RamProg

## 🚪 Why?

We are creating the Tasks Widget, so we need a list of horizontal indicators

## 🔑 What?

I extract and refactor this piece of code so we can use it to create the Tasks widget from F0

## 🏡 Context

https://www.figma.com/design/9pLsRzdinid0ha0qRWta2D/Employee-Profile?node-id=604-7408&node-type=frame&t=umPkgaSFRFR6L52Y-0

2024-09-11 07:37 UTC, sauldom102 commented on lib/components/Utilities/IndicatorsList/index.tsx
> +  }[]
We could better get these attributes from the `Indicator` component props:

```suggestion
  items: IndicatorProps[]
```

2024-09-11 07:38 UTC, sauldom102 requested changes
Are we placing widget "composables" inside "Utilities"? We should likely organize it into a common folder

2024-09-12 07:41 UTC, RamProg commented
> Are we placing widget "composables" inside "Utilities"? We should likely organize it into a common folder

I addressed all of your comments

2024-09-12 07:43 UTC, sauldom102 approved these changes
Nice! ✅

2024-09-12 08:05 UTC, merged