Create widget inbox components
factorialco/factorial-one pull request #850
Opened 2024-11-18 16:23 UTC by sauldom102

## Description

Create widget inbox components.

## Screenshots

<img width="831" alt="Screenshot 2024-11-18 at 17 23 24" src="https://github.com/user-attachments/assets/71faef35-044e-4105-9644-b831d55b0f12">

<img width="774" alt="Screenshot 2024-11-18 at 17 23 40" src="https://github.com/user-attachments/assets/28254473-b8d0-4b82-b288-6a132eccffaf">

<img width="869" alt="Screenshot 2024-11-18 at 17 23 04" src="https://github.com/user-attachments/assets/81a4eafe-d371-48ca-a5e4-3056b27618fa">

2024-11-18 16:52 UTC, eliseo-juan requested changes
Why don't we just evolve the Widget List Item to have this format of 2 rows and an Icon?
https://www.figma.com/design/pZzg1KTe9lpKTSGPUZa8OJ/Web-Components?node-id=1198-5594&t=kI70UY0qEliG9LDf-4

2024-11-18 16:54 UTC, eliseo-juan commented
I would merge both implementations and create a new component called as it is in Figma:
https://www.figma.com/design/pZzg1KTe9lpKTSGPUZa8OJ/Web-Components?node-id=1198-5594&t=kI70UY0qEliG9LDf-4

2024-11-19 09:00 UTC, sauldom102 commented
> Why don't we just evolve the Widget List Item to have this format of 2 rows and an Icon? https://www.figma.com/design/pZzg1KTe9lpKTSGPUZa8OJ/Web-Components?node-id=1198-5594&t=kI70UY0qEliG9LDf-4

I derived its name from each type shown in Figma, but it's gonna be a mess if we start adding optional props for each of the three types that we have there. Also the usage of it would be super uncertain, some of them could have counters, tags, balances, some other only a title and subtitle, ... It's just simpler to have them exported and declared separately

<img width="431" alt="Screenshot 2024-11-19 at 09 58 05" src="https://github.com/user-attachments/assets/38f77590-0e78-407c-85d7-3b27bde10361">

2024-11-19 09:01 UTC, eliseo-juan approved these changes

2024-11-19 09:02 UTC, merged